/**
 * Restaurant template configuration.
 * Customize a new client site primarily by editing this file
 * (and replacing images). Components should not hardcode brand data.
 */

export const restaurant = {
  name: 'Demos Kitchen',
  shortName: 'Demos',
  tagline: 'Bright plates. Slow-fired flavor. Ready when you are.',
  description:
    'Demos Kitchen is a fictional neighborhood kitchen serving wood-fired plates, citrus-bright salads, and late-night comfort. This template uses demo data only — swap this file to launch a new restaurant.',
  story:
    'We opened Demos Kitchen as a small counter with one oven and a citrus press. The idea was simple: cook food that feels generous, keep ordering frictionless, and never hide the details. Today the same kitchen still seasons in-house, fires bread to order, and treats pickup with the same care as a table service.',
  foundedYear: 2019,
  logo: '/logo.svg',
  heroImage:
    'https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=1600&q=80',
  aboutImage:
    'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1400&q=80',
  seo: {
    title: 'Demos Kitchen | Order Online for Delivery & Pickup',
    description:
      'Order wood-fired plates, burgers, pasta, coffee, and dessert from Demos Kitchen. Delivery and pickup in a fictional downtown neighborhood.',
  },
  contact: {
    phone: '+1 (555) 014-2098',
    phoneHref: 'tel:+15550142098',
    whatsapp: '+15550142098',
    whatsappHref: 'https://wa.me/15550142098',
    email: 'hello@demoskitchen.example',
    address: '48 Willow Arcade, Northbridge, DK 90210',
    mapUrl: 'https://www.google.com/maps/search/?api=1&query=48+Willow+Arcade+Northbridge',
  },
  colors: {
    primary: '#1F4D3A',
    secondary: '#C45C26',
    accent: '#E8B923',
    background: '#F6F1E8',
    ink: '#14201B',
    muted: '#5C6B64',
  },
  hours: [
    { day: 'Monday', open: '11:00', close: '22:00', closed: false },
    { day: 'Tuesday', open: '11:00', close: '22:00', closed: false },
    { day: 'Wednesday', open: '11:00', close: '22:00', closed: false },
    { day: 'Thursday', open: '11:00', close: '23:00', closed: false },
    { day: 'Friday', open: '11:00', close: '23:30', closed: false },
    { day: 'Saturday', open: '10:00', close: '23:30', closed: false },
    { day: 'Sunday', open: '10:00', close: '21:00', closed: false },
  ],
  delivery: {
    enabled: true,
    fee: 3.5,
    minimumOrder: 18,
    estimatedTime: '25–40 min',
    areas: [
      { id: 'northbridge', name: 'Northbridge', fee: 2.5, eta: '20–30 min', available: true },
      { id: 'willow-park', name: 'Willow Park', fee: 3.5, eta: '25–40 min', available: true },
      { id: 'harbor-row', name: 'Harbor Row', fee: 4.5, eta: '35–50 min', available: true },
      { id: 'cedar-heights', name: 'Cedar Heights', fee: 5.5, eta: '40–55 min', available: true },
      { id: 'east-quay', name: 'East Quay', fee: 6.0, eta: '45–60 min', available: false },
    ],
  },
  pickup: {
    enabled: true,
    estimatedTime: '12–18 min',
    address: '48 Willow Arcade, Northbridge, DK 90210',
    instructions: 'Enter through the arcade. Pickup shelf is on the left of the pastry counter. Quote your order number.',
  },
  stats: [
    { label: 'Plates served monthly', value: '12k+' },
    { label: 'Average prep time', value: '16 min' },
    { label: 'Guest rating', value: '4.8' },
  ],
  features: [
    {
      id: 'fresh',
      icon: 'Leaf',
      title: 'Fresh ingredients',
      description: 'Produce is prepped daily. Citrus, herbs, and breads are finished in-house.',
    },
    {
      id: 'quality',
      icon: 'UtensilsCrossed',
      title: 'Quality cooking',
      description: 'Wood-fired heat, careful seasoning, and plates built for both dine-in energy and takeaway.',
    },
    {
      id: 'ordering',
      icon: 'Smartphone',
      title: 'Easy ordering',
      description: 'Search the menu, customize extras, and checkout in a few clear steps.',
    },
    {
      id: 'delivery',
      icon: 'Bike',
      title: 'Fast handoff',
      description: 'Pickup windows and delivery ETAs are shown before you pay, not after.',
    },
  ],
  social: {
    facebook: 'https://facebook.com',
    instagram: 'https://instagram.com',
    tiktok: 'https://tiktok.com',
  },
  admin: {
    email: 'admin@demoskitchen.example',
    password: 'demo1234',
  },
  payments: [
    { id: 'cod', label: 'Cash on delivery', description: 'Pay the courier when your order arrives.', orderTypes: ['delivery'] },
    { id: 'cop', label: 'Cash on pickup', description: 'Pay at the counter when you collect.', orderTypes: ['pickup'] },
    { id: 'transfer', label: 'Bank transfer', description: 'We will email transfer instructions with your order number.', orderTypes: ['delivery', 'pickup'] },
    { id: 'online', label: 'Online payment', description: 'Placeholder for a future processor. Not charged in this demo.', orderTypes: ['delivery', 'pickup'] },
  ],
  categories: [
    {
      id: 'burgers',
      slug: 'burgers',
      name: 'Burgers',
      description: 'Griddled stacks with citrus aioli and toasted buns.',
      image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80',
      icon: 'Beef',
      enabled: true,
    },
    {
      id: 'pizza',
      slug: 'pizza',
      name: 'Wood-fired pizza',
      description: 'Thin crust, blistered edges, seasonal toppings.',
      image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=80',
      icon: 'Pizza',
      enabled: true,
    },
    {
      id: 'sandwiches',
      slug: 'sandwiches',
      name: 'Sandwiches',
      description: 'Pressed breads, slow proteins, bright pickles.',
      image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=800&q=80',
      icon: 'Sandwich',
      enabled: true,
    },
    {
      id: 'pasta',
      slug: 'pasta',
      name: 'Pasta',
      description: 'Silky sauces and handmade-style ribbons.',
      image: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?auto=format&fit=crop&w=800&q=80',
      icon: 'Utensils',
      enabled: true,
    },
    {
      id: 'bowls',
      slug: 'bowls',
      name: 'Bowls & plates',
      description: 'Grain bowls, grilled plates, and citrus salads.',
      image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80',
      icon: 'Salad',
      enabled: true,
    },
    {
      id: 'drinks',
      slug: 'drinks',
      name: 'Drinks',
      description: 'Sparkling sodas, juices, and house coolers.',
      image: 'https://images.unsplash.com/photo-1544145945-f90425316c8c?auto=format&fit=crop&w=800&q=80',
      icon: 'CupSoda',
      enabled: true,
    },
    {
      id: 'coffee',
      slug: 'coffee',
      name: 'Coffee',
      description: 'Espresso drinks and slow drip.',
      image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=800&q=80',
      icon: 'Coffee',
      enabled: true,
    },
    {
      id: 'desserts',
      slug: 'desserts',
      name: 'Desserts',
      description: 'Small sweets to finish the table.',
      image: 'https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&w=800&q=80',
      icon: 'CakeSlice',
      enabled: true,
    },
    {
      id: 'deals',
      slug: 'deals',
      name: 'Deals',
      description: 'Bundles built for sharing or weeknights.',
      image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80',
      icon: 'BadgePercent',
      enabled: true,
    },
  ],
  products: [
    {
      id: 'p-citrus-smash',
      slug: 'citrus-smash-burger',
      name: 'Citrus smash burger',
      description: 'Double smash patties, charred lemon aioli, pickle chips, and a toasted potato bun.',
      categoryId: 'burgers',
      price: 13.5,
      originalPrice: 15.0,
      image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=900&q=80',
      popular: true,
      featured: true,
      isNew: false,
      available: true,
      rating: 4.9,
      reviewCount: 214,
      tags: ['beef', 'signature', 'smash'],
      ingredients: ['Beef patties', 'Potato bun', 'Lemon aioli', 'Pickles', 'Onion'],
      allergens: ['Gluten', 'Egg', 'Dairy'],
      weight: '240 g',
      variants: [
        { id: 'regular', name: 'Regular', priceDelta: 0 },
        { id: 'large', name: 'Large (triple smash)', priceDelta: 3.5 },
      ],
      addOns: [
        { id: 'cheese', name: 'Extra cheese', price: 1.5 },
        { id: 'sauce', name: 'Extra citrus aioli', price: 0.8 },
        { id: 'egg', name: 'Fried egg', price: 1.8 },
      ],
    },
    {
      id: 'p-garden-stack',
      slug: 'garden-herb-burger',
      name: 'Garden herb burger',
      description: 'Chickpea-herb patty, whipped feta, cucumber ribbons, and chili honey.',
      categoryId: 'burgers',
      price: 12.0,
      originalPrice: null,
      image: 'https://images.unsplash.com/photo-1520072959219-c595dc870360?auto=format&fit=crop&w=900&q=80',
      popular: false,
      featured: false,
      isNew: true,
      available: true,
      rating: 4.6,
      reviewCount: 88,
      tags: ['vegetarian', 'spicy'],
      ingredients: ['Chickpea patty', 'Feta', 'Cucumber', 'Chili honey', 'Bun'],
      allergens: ['Gluten', 'Dairy'],
      weight: '220 g',
      variants: [
        { id: 'regular', name: 'Regular', priceDelta: 0 },
        { id: 'large', name: 'Large', priceDelta: 2.5 },
      ],
      addOns: [
        { id: 'cheese', name: 'Extra feta', price: 1.4 },
        { id: 'sauce', name: 'Extra chili honey', price: 0.7 },
      ],
    },
    {
      id: 'p-smokehouse',
      slug: 'smokehouse-burger',
      name: 'Smokehouse burger',
      description: 'Dry-rub patty, smoked cheddar, charred onion jam, and crisp lettuce.',
      categoryId: 'burgers',
      price: 14.25,
      originalPrice: null,
      image: 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?auto=format&fit=crop&w=900&q=80',
      popular: true,
      featured: false,
      isNew: false,
      available: true,
      rating: 4.7,
      reviewCount: 151,
      tags: ['beef', 'smoky'],
      ingredients: ['Beef', 'Smoked cheddar', 'Onion jam', 'Lettuce', 'Bun'],
      allergens: ['Gluten', 'Dairy'],
      weight: '260 g',
      variants: [
        { id: 'regular', name: 'Regular', priceDelta: 0 },
        { id: 'large', name: 'Large', priceDelta: 3 },
      ],
      addOns: [
        { id: 'cheese', name: 'Extra cheddar', price: 1.5 },
        { id: 'egg', name: 'Fried egg', price: 1.8 },
      ],
    },
    {
      id: 'p-citrus-margherita',
      slug: 'citrus-margherita',
      name: 'Citrus margherita',
      description: 'San Marzano tomato, fior di latte, basil oil, and a whisper of lemon zest.',
      categoryId: 'pizza',
      price: 16.0,
      originalPrice: 18.0,
      image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=900&q=80',
      popular: true,
      featured: true,
      isNew: false,
      available: true,
      rating: 4.8,
      reviewCount: 301,
      tags: ['vegetarian', 'wood-fired'],
      ingredients: ['Tomato', 'Mozzarella', 'Basil', 'Lemon zest'],
      allergens: ['Gluten', 'Dairy'],
      weight: '420 g',
      variants: [
        { id: 'regular', name: 'Regular 10"', priceDelta: 0 },
        { id: 'large', name: 'Large 14"', priceDelta: 5 },
      ],
      addOns: [
        { id: 'cheese', name: 'Extra mozzarella', price: 2 },
        { id: 'sauce', name: 'Chili oil', price: 0.9 },
      ],
    },
    {
      id: 'p-wild-mushroom',
      slug: 'wild-mushroom-pizza',
      name: 'Wild mushroom pizza',
      description: 'Roasted fungi, thyme cream, pecorino, and cracked pepper.',
      categoryId: 'pizza',
      price: 18.5,
      originalPrice: null,
      image: 'https://images.unsplash.com/photo-1604068549290-dea0e4a305ca?auto=format&fit=crop&w=900&q=80',
      popular: false,
      featured: false,
      isNew: false,
      available: true,
      rating: 4.5,
      reviewCount: 97,
      tags: ['vegetarian', 'earthy'],
      ingredients: ['Mushrooms', 'Thyme cream', 'Pecorino', 'Dough'],
      allergens: ['Gluten', 'Dairy'],
      weight: '450 g',
      variants: [
        { id: 'regular', name: 'Regular 10"', priceDelta: 0 },
        { id: 'large', name: 'Large 14"', priceDelta: 5 },
      ],
      addOns: [
        { id: 'cheese', name: 'Extra pecorino', price: 1.8 },
        { id: 'egg', name: 'Soft egg', price: 1.8 },
      ],
    },
    {
      id: 'p-nduja',
      slug: 'nduja-honey-pizza',
      name: 'Nduja & honey pizza',
      description: 'Spicy nduja, fior di latte, hot honey, and oregano.',
      categoryId: 'pizza',
      price: 19.0,
      originalPrice: null,
      image: 'https://images.unsplash.com/photo-1594007654729-407eedc4be65?auto=format&fit=crop&w=900&q=80',
      popular: true,
      featured: false,
      isNew: true,
      available: true,
      rating: 4.9,
      reviewCount: 176,
      tags: ['spicy', 'signature'],
      ingredients: ['Nduja', 'Mozzarella', 'Honey', 'Oregano'],
      allergens: ['Gluten', 'Dairy'],
      weight: '440 g',
      variants: [
        { id: 'regular', name: 'Regular 10"', priceDelta: 0 },
        { id: 'large', name: 'Large 14"', priceDelta: 5.5 },
      ],
      addOns: [
        { id: 'sauce', name: 'Extra hot honey', price: 1 },
        { id: 'cheese', name: 'Extra cheese', price: 2 },
      ],
    },
    {
      id: 'p-pressed-chicken',
      slug: 'pressed-citrus-chicken',
      name: 'Pressed citrus chicken',
      description: 'Herb chicken, preserved lemon mayo, rocket, and toasted focaccia.',
      categoryId: 'sandwiches',
      price: 11.75,
      originalPrice: null,
      image: 'https://images.unsplash.com/photo-1554433607-66b5efe9d304?auto=format&fit=crop&w=900&q=80',
      popular: true,
      featured: false,
      isNew: false,
      available: true,
      rating: 4.7,
      reviewCount: 132,
      tags: ['chicken', 'lunch'],
      ingredients: ['Chicken', 'Focaccia', 'Rocket', 'Preserved lemon mayo'],
      allergens: ['Gluten', 'Egg'],
      weight: '280 g',
      variants: [
        { id: 'regular', name: 'Regular', priceDelta: 0 },
        { id: 'large', name: 'Large', priceDelta: 2.25 },
      ],
      addOns: [
        { id: 'cheese', name: 'Extra cheese', price: 1.4 },
        { id: 'sauce', name: 'Extra mayo', price: 0.6 },
      ],
    },
    {
      id: 'p-roast-veg',
      slug: 'roast-vegetable-melt',
      name: 'Roast vegetable melt',
      description: 'Charred zucchini, pepper, ricotta salata, and salsa verde on sourdough.',
      categoryId: 'sandwiches',
      price: 10.5,
      originalPrice: 12.0,
      image: 'https://images.unsplash.com/photo-1481070414801-51fd732d7184?auto=format&fit=crop&w=900&q=80',
      popular: false,
      featured: false,
      isNew: false,
      available: true,
      rating: 4.4,
      reviewCount: 64,
      tags: ['vegetarian'],
      ingredients: ['Zucchini', 'Pepper', 'Ricotta salata', 'Sourdough'],
      allergens: ['Gluten', 'Dairy'],
      weight: '250 g',
      variants: [
        { id: 'regular', name: 'Regular', priceDelta: 0 },
        { id: 'large', name: 'Large', priceDelta: 2 },
      ],
      addOns: [{ id: 'cheese', name: 'Extra cheese', price: 1.4 }],
    },
    {
      id: 'p-tuna-crisp',
      slug: 'seared-tuna-crisp',
      name: 'Seared tuna crisp',
      description: 'Seared tuna, sesame, pickled chili, and soft herbs on milk bread.',
      categoryId: 'sandwiches',
      price: 13.9,
      originalPrice: null,
      image: 'https://images.unsplash.com/photo-1475090169767-40ed8d18f67d?auto=format&fit=crop&w=900&q=80',
      popular: false,
      featured: true,
      isNew: true,
      available: false,
      rating: 4.6,
      reviewCount: 41,
      tags: ['seafood', 'limited'],
      ingredients: ['Tuna', 'Milk bread', 'Sesame', 'Chili'],
      allergens: ['Gluten', 'Fish', 'Sesame'],
      weight: '230 g',
      variants: [{ id: 'regular', name: 'Regular', priceDelta: 0 }],
      addOns: [{ id: 'sauce', name: 'Extra chili oil', price: 0.8 }],
    },
    {
      id: 'p-cacio',
      slug: 'cacio-e-pepe',
      name: 'Cacio e pepe',
      description: 'Tonnarelli, pecorino, black pepper, and a knob of butter.',
      categoryId: 'pasta',
      price: 15.5,
      originalPrice: null,
      image: 'https://images.unsplash.com/photo-1612874742237-65262258ea32?auto=format&fit=crop&w=900&q=80',
      popular: true,
      featured: false,
      isNew: false,
      available: true,
      rating: 4.8,
      reviewCount: 188,
      tags: ['vegetarian', 'classic'],
      ingredients: ['Pasta', 'Pecorino', 'Pepper', 'Butter'],
      allergens: ['Gluten', 'Dairy'],
      weight: '380 g',
      variants: [
        { id: 'regular', name: 'Regular', priceDelta: 0 },
        { id: 'large', name: 'Large', priceDelta: 3.5 },
      ],
      addOns: [
        { id: 'cheese', name: 'Extra pecorino', price: 1.6 },
        { id: 'egg', name: 'Soft egg', price: 1.8 },
      ],
    },
    {
      id: 'p-lemon-prawn',
      slug: 'lemon-prawn-linguine',
      name: 'Lemon prawn linguine',
      description: 'Prawns, garlic, chili, parsley, and plenty of lemon.',
      categoryId: 'pasta',
      price: 18.75,
      originalPrice: null,
      image: 'https://images.unsplash.com/photo-1563379926898-05f4575a45d8?auto=format&fit=crop&w=900&q=80',
      popular: true,
      featured: true,
      isNew: false,
      available: true,
      rating: 4.9,
      reviewCount: 143,
      tags: ['seafood', 'signature'],
      ingredients: ['Linguine', 'Prawns', 'Garlic', 'Lemon', 'Chili'],
      allergens: ['Gluten', 'Shellfish'],
      weight: '400 g',
      variants: [
        { id: 'regular', name: 'Regular', priceDelta: 0 },
        { id: 'large', name: 'Large', priceDelta: 4 },
      ],
      addOns: [
        { id: 'sauce', name: 'Extra lemon butter', price: 1.2 },
        { id: 'chili', name: 'Extra chili', price: 0.5 },
      ],
    },
    {
      id: 'p-sage-ravioli',
      slug: 'brown-butter-ravioli',
      name: 'Brown butter ravioli',
      description: 'Ricotta pillows, sage, toasted hazelnut, and brown butter.',
      categoryId: 'pasta',
      price: 17.25,
      originalPrice: 19.0,
      image: 'https://images.unsplash.com/photo-1587740901105-e1bb0a8c2a0a?auto=format&fit=crop&w=900&q=80',
      popular: false,
      featured: false,
      isNew: false,
      available: true,
      rating: 4.5,
      reviewCount: 72,
      tags: ['vegetarian'],
      ingredients: ['Ravioli', 'Ricotta', 'Sage', 'Hazelnut', 'Butter'],
      allergens: ['Gluten', 'Dairy', 'Nuts'],
      weight: '360 g',
      variants: [{ id: 'regular', name: 'Regular', priceDelta: 0 }],
      addOns: [{ id: 'cheese', name: 'Extra parmesan', price: 1.5 }],
    },
    {
      id: 'p-citrus-grain',
      slug: 'citrus-grain-bowl',
      name: 'Citrus grain bowl',
      description: 'Farro, roasted squash, orange segments, pistachio, and yogurt tahini.',
      categoryId: 'bowls',
      price: 13.0,
      originalPrice: null,
      image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=80',
      popular: true,
      featured: false,
      isNew: false,
      available: true,
      rating: 4.7,
      reviewCount: 119,
      tags: ['vegetarian', 'bowl'],
      ingredients: ['Farro', 'Squash', 'Orange', 'Pistachio', 'Yogurt'],
      allergens: ['Gluten', 'Dairy', 'Nuts'],
      weight: '420 g',
      variants: [
        { id: 'regular', name: 'Regular', priceDelta: 0 },
        { id: 'large', name: 'Large', priceDelta: 2.5 },
      ],
      addOns: [
        { id: 'egg', name: 'Soft egg', price: 1.8 },
        { id: 'chicken', name: 'Grilled chicken', price: 3.5 },
      ],
    },
    {
      id: 'p-char-plate',
      slug: 'charred-market-plate',
      name: 'Charred market plate',
      description: 'Seasonal vegetables, herb oil, labneh, and warm flatbread.',
      categoryId: 'bowls',
      price: 14.5,
      originalPrice: null,
      image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&w=900&q=80',
      popular: false,
      featured: true,
      isNew: false,
      available: true,
      rating: 4.6,
      reviewCount: 83,
      tags: ['vegetarian', 'share'],
      ingredients: ['Market vegetables', 'Labneh', 'Herb oil', 'Flatbread'],
      allergens: ['Gluten', 'Dairy'],
      weight: '480 g',
      variants: [{ id: 'regular', name: 'Regular', priceDelta: 0 }],
      addOns: [{ id: 'chicken', name: 'Grilled chicken', price: 3.5 }],
    },
    {
      id: 'p-salmon-plate',
      slug: 'citrus-salmon-plate',
      name: 'Citrus salmon plate',
      description: 'Roasted salmon, fennel salad, blood orange, and dill yogurt.',
      categoryId: 'bowls',
      price: 19.5,
      originalPrice: null,
      image: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=900&q=80',
      popular: true,
      featured: false,
      isNew: true,
      available: true,
      rating: 4.8,
      reviewCount: 90,
      tags: ['seafood', 'gluten-free'],
      ingredients: ['Salmon', 'Fennel', 'Blood orange', 'Dill yogurt'],
      allergens: ['Fish', 'Dairy'],
      weight: '390 g',
      variants: [{ id: 'regular', name: 'Regular', priceDelta: 0 }],
      addOns: [{ id: 'sauce', name: 'Extra dill yogurt', price: 0.9 }],
    },
    {
      id: 'p-sparkling-citrus',
      slug: 'sparkling-citrus-cooler',
      name: 'Sparkling citrus cooler',
      description: 'Orange, grapefruit, mint, and soda over crushed ice.',
      categoryId: 'drinks',
      price: 4.5,
      originalPrice: null,
      image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=900&q=80',
      popular: true,
      featured: false,
      isNew: false,
      available: true,
      rating: 4.7,
      reviewCount: 210,
      tags: ['refreshing', 'no caffeine'],
      ingredients: ['Orange', 'Grapefruit', 'Mint', 'Soda'],
      allergens: [],
      weight: '400 ml',
      variants: [
        { id: 'regular', name: 'Regular', priceDelta: 0 },
        { id: 'large', name: 'Large', priceDelta: 1.2 },
      ],
      addOns: [{ id: 'ginger', name: 'Ginger syrup', price: 0.6 }],
    },
    {
      id: 'p-house-cola',
      slug: 'house-cola',
      name: 'House cola',
      description: 'Spice-forward cola with orange peel and a clean finish.',
      categoryId: 'drinks',
      price: 3.75,
      originalPrice: null,
      image: 'https://images.unsplash.com/photo-1527960471264-932f39eb5846?auto=format&fit=crop&w=900&q=80',
      popular: false,
      featured: false,
      isNew: false,
      available: true,
      rating: 4.3,
      reviewCount: 55,
      tags: ['soda'],
      ingredients: ['Cola', 'Orange peel'],
      allergens: [],
      weight: '330 ml',
      variants: [{ id: 'regular', name: 'Regular', priceDelta: 0 }],
      addOns: [],
    },
    {
      id: 'p-ginger-fizz',
      slug: 'ginger-lime-fizz',
      name: 'Ginger lime fizz',
      description: 'Fresh ginger, lime, honey, and sparkling water.',
      categoryId: 'drinks',
      price: 4.25,
      originalPrice: 4.75,
      image: 'https://images.unsplash.com/photo-1546173159-315724a31696?auto=format&fit=crop&w=900&q=80',
      popular: false,
      featured: false,
      isNew: true,
      available: true,
      rating: 4.5,
      reviewCount: 47,
      tags: ['refreshing'],
      ingredients: ['Ginger', 'Lime', 'Honey', 'Sparkling water'],
      allergens: [],
      weight: '380 ml',
      variants: [
        { id: 'regular', name: 'Regular', priceDelta: 0 },
        { id: 'large', name: 'Large', priceDelta: 1 },
      ],
      addOns: [{ id: 'mint', name: 'Extra mint', price: 0.4 }],
    },
    {
      id: 'p-flat-white',
      slug: 'flat-white',
      name: 'Flat white',
      description: 'Double espresso with steamed milk and a silk microfoam.',
      categoryId: 'coffee',
      price: 4.2,
      originalPrice: null,
      image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=900&q=80',
      popular: true,
      featured: false,
      isNew: false,
      available: true,
      rating: 4.8,
      reviewCount: 260,
      tags: ['espresso', 'milk'],
      ingredients: ['Espresso', 'Milk'],
      allergens: ['Dairy'],
      weight: '180 ml',
      variants: [
        { id: 'regular', name: 'Regular', priceDelta: 0 },
        { id: 'large', name: 'Large', priceDelta: 0.8 },
      ],
      addOns: [
        { id: 'oat', name: 'Oat milk', price: 0.6 },
        { id: 'shot', name: 'Extra shot', price: 0.9 },
      ],
    },
    {
      id: 'p-pour-over',
      slug: 'citrus-pour-over',
      name: 'Citrus pour-over',
      description: 'Seasonal filter coffee with notes of orange blossom and cocoa.',
      categoryId: 'coffee',
      price: 4.8,
      originalPrice: null,
      image: 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=900&q=80',
      popular: false,
      featured: true,
      isNew: false,
      available: true,
      rating: 4.6,
      reviewCount: 74,
      tags: ['filter', 'black'],
      ingredients: ['Filter coffee'],
      allergens: [],
      weight: '250 ml',
      variants: [{ id: 'regular', name: 'Regular', priceDelta: 0 }],
      addOns: [],
    },
    {
      id: 'p-mocha',
      slug: 'hearth-mocha',
      name: 'Hearth mocha',
      description: 'Espresso, dark cocoa, steamed milk, and a pinch of smoked salt.',
      categoryId: 'coffee',
      price: 5.1,
      originalPrice: null,
      image: 'https://images.unsplash.com/photo-1572442388796-11644938ec9a?auto=format&fit=crop&w=900&q=80',
      popular: false,
      featured: false,
      isNew: true,
      available: true,
      rating: 4.4,
      reviewCount: 39,
      tags: ['espresso', 'chocolate'],
      ingredients: ['Espresso', 'Cocoa', 'Milk'],
      allergens: ['Dairy'],
      weight: '240 ml',
      variants: [
        { id: 'regular', name: 'Regular', priceDelta: 0 },
        { id: 'large', name: 'Large', priceDelta: 0.9 },
      ],
      addOns: [{ id: 'oat', name: 'Oat milk', price: 0.6 }],
    },
    {
      id: 'p-olive-oil-cake',
      slug: 'citrus-olive-oil-cake',
      name: 'Citrus olive oil cake',
      description: 'Tender crumb, orange glaze, and pistachio dust.',
      categoryId: 'desserts',
      price: 6.5,
      originalPrice: null,
      image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=900&q=80',
      popular: true,
      featured: false,
      isNew: false,
      available: true,
      rating: 4.9,
      reviewCount: 167,
      tags: ['cake', 'vegetarian'],
      ingredients: ['Olive oil', 'Orange', 'Pistachio', 'Flour'],
      allergens: ['Gluten', 'Egg', 'Nuts'],
      weight: '140 g',
      variants: [{ id: 'regular', name: 'Slice', priceDelta: 0 }],
      addOns: [{ id: 'cream', name: 'Whipped cream', price: 0.8 }],
    },
    {
      id: 'p-affogato',
      slug: 'affogato',
      name: 'Affogato',
      description: 'Vanilla gelato drowned in hot espresso.',
      categoryId: 'desserts',
      price: 5.75,
      originalPrice: null,
      image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=900&q=80',
      popular: true,
      featured: false,
      isNew: false,
      available: true,
      rating: 4.8,
      reviewCount: 102,
      tags: ['coffee', 'gelato'],
      ingredients: ['Gelato', 'Espresso'],
      allergens: ['Dairy'],
      weight: '150 g',
      variants: [{ id: 'regular', name: 'Regular', priceDelta: 0 }],
      addOns: [{ id: 'shot', name: 'Extra espresso', price: 0.9 }],
    },
    {
      id: 'p-chocolate-pot',
      slug: 'dark-chocolate-pot',
      name: 'Dark chocolate pot',
      description: '70% ganache, sea salt, and olive oil.',
      categoryId: 'desserts',
      price: 6.25,
      originalPrice: 7.0,
      image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=900&q=80',
      popular: false,
      featured: false,
      isNew: false,
      available: true,
      rating: 4.7,
      reviewCount: 81,
      tags: ['chocolate', 'gluten-free'],
      ingredients: ['Chocolate', 'Cream', 'Olive oil', 'Salt'],
      allergens: ['Dairy'],
      weight: '120 g',
      variants: [{ id: 'regular', name: 'Regular', priceDelta: 0 }],
      addOns: [{ id: 'cream', name: 'Cream', price: 0.8 }],
    },
    {
      id: 'p-weeknight-duo',
      slug: 'weeknight-duo',
      name: 'Weeknight duo',
      description: 'Any regular burger plus a sparkling cooler. Built for Tuesday energy.',
      categoryId: 'deals',
      price: 15.5,
      originalPrice: 18.0,
      image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=900&q=80',
      popular: true,
      featured: true,
      isNew: false,
      available: true,
      rating: 4.6,
      reviewCount: 58,
      tags: ['bundle', 'value'],
      ingredients: ['Burger', 'Cooler'],
      allergens: ['See burger allergens'],
      weight: 'Combo',
      variants: [
        { id: 'smash', name: 'Citrus smash + cooler', priceDelta: 0 },
        { id: 'garden', name: 'Garden herb + cooler', priceDelta: -0.5 },
      ],
      addOns: [{ id: 'fries-note', name: 'Add extra sauce', price: 0.8 }],
    },
    {
      id: 'p-table-for-two',
      slug: 'table-for-two',
      name: 'Table for two',
      description: 'One regular pizza, two drinks, and a dessert to share.',
      categoryId: 'deals',
      price: 32.0,
      originalPrice: 38.0,
      image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=900&q=80',
      popular: true,
      featured: false,
      isNew: false,
      available: true,
      rating: 4.8,
      reviewCount: 94,
      tags: ['bundle', 'share'],
      ingredients: ['Pizza', 'Drinks', 'Dessert'],
      allergens: ['See individual items'],
      weight: 'Combo',
      variants: [
        { id: 'margherita', name: 'Margherita set', priceDelta: 0 },
        { id: 'nduja', name: 'Nduja set', priceDelta: 2.5 },
      ],
      addOns: [{ id: 'cheese', name: 'Extra cheese on pizza', price: 2 }],
    },
    {
      id: 'p-lunch-express',
      slug: 'lunch-express',
      name: 'Lunch express',
      description: 'Pressed sandwich, coffee, and a cookie note from the pastry counter.',
      categoryId: 'deals',
      price: 14.0,
      originalPrice: 16.5,
      image: 'https://images.unsplash.com/photo-1554433607-66b5efe9d304?auto=format&fit=crop&w=900&q=80',
      popular: false,
      featured: false,
      isNew: true,
      available: true,
      rating: 4.5,
      reviewCount: 36,
      tags: ['bundle', 'lunch'],
      ingredients: ['Sandwich', 'Coffee', 'Cookie'],
      allergens: ['Gluten', 'Dairy'],
      weight: 'Combo',
      variants: [{ id: 'regular', name: 'Regular', priceDelta: 0 }],
      addOns: [{ id: 'oat', name: 'Oat milk coffee', price: 0.6 }],
    },
  ],
  offers: [
    {
      id: 'o-weekday',
      title: 'Weekday noon lift',
      description: '15% off orders over $25, Monday to Thursday before 3pm.',
      discount: '15% off',
      discountType: 'percent',
      discountValue: 15,
      minSubtotal: 25,
      code: 'NOON15',
      validUntil: '2026-12-31',
      image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1200&q=80',
      productIds: ['p-lunch-express', 'p-pressed-chicken'],
      active: true,
      featured: true,
      cta: 'Order the lunch set',
    },
    {
      id: 'o-family',
      title: 'Table for two nights',
      description: 'Save on the pizza, drinks, and dessert bundle after 5pm.',
      discount: '$6 off bundle',
      discountType: 'fixed',
      discountValue: 6,
      minSubtotal: 0,
      code: 'TWONIGHT',
      validUntil: '2026-11-30',
      image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1200&q=80',
      productIds: ['p-table-for-two'],
      active: true,
      featured: true,
      cta: 'View the bundle',
    },
    {
      id: 'o-first',
      title: 'First order citrus welcome',
      description: 'New guests get $5 off delivery orders over $30.',
      discount: '$5 off',
      discountType: 'fixed',
      discountValue: 5,
      minSubtotal: 30,
      code: 'WELCOME5',
      validUntil: '2026-12-31',
      image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=1200&q=80',
      productIds: [],
      active: true,
      featured: false,
      cta: 'Start an order',
    },
    {
      id: 'o-dessert',
      title: 'Sweet finish',
      description: 'Free whipped cream on any dessert this month.',
      discount: 'Free extra',
      discountType: 'percent',
      discountValue: 0,
      minSubtotal: 0,
      code: 'SWEET',
      validUntil: '2026-10-31',
      image: 'https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&w=1200&q=80',
      productIds: ['p-olive-oil-cake', 'p-chocolate-pot', 'p-affogato'],
      active: true,
      featured: false,
      cta: 'See desserts',
    },
  ],
  reviews: [
    {
      id: 'r1',
      name: 'Maya Ellison',
      avatar: 'https://i.pravatar.cc/96?img=47',
      location: 'Northbridge',
      rating: 5,
      date: '2026-08-12',
      text: 'The citrus smash is the reason we keep coming back. Pickup was ready in 14 minutes and still hot.',
      verified: true,
      helpful: 18,
      featured: true,
      status: 'approved',
      categoryRatings: { food: 5, service: 5, delivery: 4, packaging: 5 },
    },
    {
      id: 'r2',
      name: 'Jonah Patel',
      avatar: 'https://i.pravatar.cc/96?img=12',
      location: 'Willow Park',
      rating: 5,
      date: '2026-08-02',
      text: 'Nduja pizza had blistered edges and the hot honey actually belonged there. Delivery tracking was clear.',
      verified: true,
      helpful: 11,
      featured: false,
      status: 'approved',
      categoryRatings: { food: 5, service: 4, delivery: 5, packaging: 5 },
    },
    {
      id: 'r3',
      name: 'Priya Rahman',
      avatar: 'https://i.pravatar.cc/96?img=32',
      location: 'Harbor Row',
      rating: 4,
      date: '2026-07-21',
      text: 'Grain bowl was bright and filling. Courier was a little later than the window, food still traveled well.',
      verified: true,
      helpful: 7,
      featured: false,
      status: 'approved',
      categoryRatings: { food: 5, service: 4, delivery: 3, packaging: 4 },
    },
    {
      id: 'r4',
      name: 'Eli Navarro',
      avatar: 'https://i.pravatar.cc/96?img=15',
      location: 'Cedar Heights',
      rating: 5,
      date: '2026-07-09',
      text: 'Olive oil cake is quietly excellent. Ordered dessert with coffee for pickup — seamless.',
      verified: true,
      helpful: 9,
      featured: true,
      status: 'approved',
      categoryRatings: { food: 5, service: 5, delivery: 5, packaging: 4 },
    },
    {
      id: 'r5',
      name: 'Sofia Berg',
      avatar: 'https://i.pravatar.cc/96?img=20',
      location: 'Northbridge',
      rating: 4,
      date: '2026-06-28',
      text: 'Pressed chicken sandwich is our weekday default. Would love a larger drink size in the lunch express.',
      verified: false,
      helpful: 4,
      featured: false,
      status: 'approved',
      categoryRatings: { food: 4, service: 4, delivery: 4, packaging: 4 },
    },
    {
      id: 'r6',
      name: 'Chris Adeyemi',
      avatar: 'https://i.pravatar.cc/96?img=8',
      location: 'Willow Park',
      rating: 5,
      date: '2026-06-14',
      text: 'Staff packed sauces separately and the pasta still felt restaurant-quality at home.',
      verified: true,
      helpful: 13,
      featured: false,
      status: 'approved',
      categoryRatings: { food: 5, service: 5, delivery: 5, packaging: 5 },
    },
    {
      id: 'r7',
      name: 'Hannah Cole',
      avatar: 'https://i.pravatar.cc/96?img=24',
      location: 'Harbor Row',
      rating: 3,
      date: '2026-05-30',
      text: 'Flavors were good, but the large pizza was a bit oilier than I wanted. Still would reorder the cooler.',
      verified: true,
      helpful: 2,
      featured: false,
      status: 'approved',
      categoryRatings: { food: 3, service: 4, delivery: 4, packaging: 3 },
    },
    {
      id: 'r8',
      name: 'Leo Hart',
      avatar: 'https://i.pravatar.cc/96?img=5',
      location: 'Northbridge',
      rating: 5,
      date: '2026-05-11',
      text: 'Best weekday pickup near the arcade. The app-like flow on this site made customizing extras easy.',
      verified: true,
      helpful: 16,
      featured: false,
      status: 'approved',
      categoryRatings: { food: 5, service: 5, delivery: 4, packaging: 5 },
    },
  ],
  gallery: [
    {
      id: 'g1',
      src: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=1400&q=80',
      alt: 'Dining room with warm lighting and set tables',
    },
    {
      id: 'g2',
      src: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1400&q=80',
      alt: 'Plated dishes on a wooden table',
    },
    {
      id: 'g3',
      src: 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=1400&q=80',
      alt: 'Close-up of a smash burger',
    },
    {
      id: 'g4',
      src: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=1400&q=80',
      alt: 'Wood-fired pizza with melted cheese',
    },
    {
      id: 'g5',
      src: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1400&q=80',
      alt: 'Coffee being poured into a cup',
    },
    {
      id: 'g6',
      src: 'https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&w=1400&q=80',
      alt: 'Dessert with citrus garnish',
    },
  ],
};

export default restaurant;
